name: angular_github_search
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^7.0.0
  angular_bloc: ^8.0.0
  bloc: ^8.1.0
  common_github_search:
    path: ../common_github_search
dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  very_good_analysis: ^3.0.1